# User Test
#------------------------------------------


USER_APP_C  =   $(wildcard  ./*.c)


TEST_C = $(USER_APP_C) 

PLPBRIDGE_FLAGS += -ftdi
include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk






