# User Test
#------------------------------------------
TEST_C          = $(wildcard  ./*.c)

#INC            += $(GAP_SDK_HOME)/examples/mbed-examples/GAPUINO_BSP/Components/himax $(GAP_SDK_HOME)/examples/mbed-examples/Driver


PLPBRIDGE_FLAGS += -ftdi


include $(GAP_SDK_HOME)/tools/rules/mbed_rules.mk
